global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "auth-api"

scrape_configs:
  - job_name: "auth-api"
    static_configs:
      - targets: ["api:8080"]
    metrics_path: "/metrics"
    scrape_interval: 10s
